import { Dataset } from '../types';

export const SAMPLE_DATASETS: Dataset[] = [
  {
    id: 'ds-healthcare-01',
    projectId: 'proj-clinical-ops',
    name: 'Clinical Vitals & Inpatient Outcomes',
    description: 'Patient admissions, vital signs, length of stay, biomarker readings, and readmission risk across hospital departments.',
    domain: 'Healthcare & Clinical Analytics',
    rowCount: 240,
    columnCount: 8,
    fileType: 'csv',
    status: 'ready',
    sizeBytes: 145200,
    uploadedAt: '2026-08-14T09:30:00Z',
    tags: ['clinical', 'vitals', 'icu', 'outcomes'],
    columns: [
      { name: 'Patient ID', key: 'patient_id', originalName: 'patient_id', dataType: 'id', description: 'Unique anonymized inpatient identifier' },
      { name: 'Admission Date', key: 'admission_date', originalName: 'admission_date', dataType: 'datetime', description: 'Date of hospital admission' },
      { name: 'Department', key: 'department', originalName: 'department', dataType: 'categorical', description: 'Hospital ward or clinical unit' },
      { name: 'Systolic BP (mmHg)', key: 'systolic_bp', originalName: 'systolic_bp', dataType: 'numeric', description: 'Patient systolic blood pressure reading' },
      { name: 'Blood Glucose (mg/dL)', key: 'blood_glucose', originalName: 'blood_glucose', dataType: 'numeric', description: 'Fasting blood sugar level' },
      { name: 'Oxygen Saturation (%)', key: 'spo2_pct', originalName: 'spo2_pct', dataType: 'numeric', description: 'Blood pulse oximetry level' },
      { name: 'Length of Stay (Days)', key: 'length_of_stay_days', originalName: 'length_of_stay_days', dataType: 'numeric', description: 'Inpatient duration in days' },
      { name: 'Readmission Risk Score', key: 'readmission_risk', originalName: 'readmission_risk', dataType: 'numeric', description: 'Algorithmic 30-day readmit probability (0-100)' }
    ],
    sampleRows: [
      { patient_id: 'PT-8801', admission_date: '2026-07-01', department: 'Cardiology', systolic_bp: 148, blood_glucose: 142, spo2_pct: 95.2, length_of_stay_days: 5.4, readmission_risk: 68 },
      { patient_id: 'PT-8802', admission_date: '2026-07-03', department: 'Neurology', systolic_bp: 122, blood_glucose: 104, spo2_pct: 98.4, length_of_stay_days: 3.1, readmission_risk: 24 },
      { patient_id: 'PT-8803', admission_date: '2026-07-05', department: 'Intensive Care (ICU)', systolic_bp: 165, blood_glucose: 188, spo2_pct: 91.8, length_of_stay_days: 9.8, readmission_risk: 84 },
      { patient_id: 'PT-8804', admission_date: '2026-07-08', department: 'Orthopedics', systolic_bp: 118, blood_glucose: 96, spo2_pct: 99.1, length_of_stay_days: 2.2, readmission_risk: 12 },
      { patient_id: 'PT-8805', admission_date: '2026-07-11', department: 'General Internal', systolic_bp: 134, blood_glucose: 128, spo2_pct: 96.5, length_of_stay_days: 4.0, readmission_risk: 42 },
      { patient_id: 'PT-8806', admission_date: '2026-07-14', department: 'Cardiology', systolic_bp: 152, blood_glucose: 160, spo2_pct: 94.0, length_of_stay_days: 6.2, readmission_risk: 72 },
      { patient_id: 'PT-8807', admission_date: '2026-07-17', department: 'Intensive Care (ICU)', systolic_bp: 172, blood_glucose: 210, spo2_pct: 89.4, length_of_stay_days: 11.5, readmission_risk: 91 },
      { patient_id: 'PT-8808', admission_date: '2026-07-20', department: 'Neurology', systolic_bp: 128, blood_glucose: 112, spo2_pct: 97.6, length_of_stay_days: 3.8, readmission_risk: 31 },
      { patient_id: 'PT-8809', admission_date: '2026-07-23', department: 'General Internal', systolic_bp: 130, blood_glucose: 118, spo2_pct: 97.0, length_of_stay_days: 3.5, readmission_risk: 38 },
      { patient_id: 'PT-8810', admission_date: '2026-07-26', department: 'Orthopedics', systolic_bp: 115, blood_glucose: 92, spo2_pct: 99.3, length_of_stay_days: 1.9, readmission_risk: 9 },
      { patient_id: 'PT-8811', admission_date: '2026-07-29', department: 'Intensive Care (ICU)', systolic_bp: 168, blood_glucose: 195, spo2_pct: 90.5, length_of_stay_days: 10.2, readmission_risk: 88 },
      { patient_id: 'PT-8812', admission_date: '2026-08-01', department: 'Cardiology', systolic_bp: 144, blood_glucose: 136, spo2_pct: 95.8, length_of_stay_days: 4.8, readmission_risk: 58 },
      { patient_id: 'PT-8813', admission_date: '2026-08-04', department: 'General Internal', systolic_bp: 138, blood_glucose: 145, spo2_pct: 95.0, length_of_stay_days: 4.6, readmission_risk: 49 },
      { patient_id: 'PT-8814', admission_date: '2026-08-07', department: 'Neurology', systolic_bp: 120, blood_glucose: 100, spo2_pct: 98.2, length_of_stay_days: 2.8, readmission_risk: 20 },
      { patient_id: 'PT-8815', admission_date: '2026-08-10', department: 'Orthopedics', systolic_bp: 116, blood_glucose: 94, spo2_pct: 99.0, length_of_stay_days: 2.0, readmission_risk: 11 }
    ]
  },
  {
    id: 'ds-logistics-02',
    projectId: 'proj-supply-chain',
    name: 'Freight Transit & Fleet Telemetry',
    description: 'Cargo dispatches, payload weights, route transit duration, fuel burn rate, and on-time arrival metrics across logistics corridors.',
    domain: 'Logistics & Supply Chain',
    rowCount: 320,
    columnCount: 8,
    fileType: 'csv',
    status: 'ready',
    sizeBytes: 182400,
    uploadedAt: '2026-08-12T14:15:00Z',
    tags: ['freight', 'fleet', 'transit', 'efficiency'],
    columns: [
      { name: 'Shipment Waybill', key: 'waybill_id', originalName: 'waybill_id', dataType: 'id', description: 'Unique freight shipment ID' },
      { name: 'Dispatch Date', key: 'dispatch_date', originalName: 'dispatch_date', dataType: 'datetime', description: 'Depot departure timestamp' },
      { name: 'Corridor Hub', key: 'corridor_hub', originalName: 'corridor_hub', dataType: 'categorical', description: 'Primary logistics transit corridor' },
      { name: 'Cargo Weight (Tons)', key: 'cargo_weight_tons', originalName: 'cargo_weight_tons', dataType: 'numeric', description: 'Total payload mass in metric tons' },
      { name: 'Transit Duration (Hours)', key: 'transit_duration_hrs', originalName: 'transit_duration_hrs', dataType: 'numeric', description: 'Elapsed hours from hub to destination' },
      { name: 'Fuel Consumption (Liters)', key: 'fuel_liters', originalName: 'fuel_liters', dataType: 'numeric', description: 'Total diesel consumed on trip' },
      { name: 'Engine Idle Time (Mins)', key: 'idle_time_mins', originalName: 'idle_time_mins', dataType: 'numeric', description: 'Non-moving engine runtime' },
      { name: 'Route Efficiency Index', key: 'efficiency_index', originalName: 'efficiency_index', dataType: 'numeric', description: 'Composite operational score (0-100)' }
    ],
    sampleRows: [
      { waybill_id: 'WB-4001', dispatch_date: '2026-07-02', corridor_hub: 'Pacific Gateway', cargo_weight_tons: 24.5, transit_duration_hrs: 18.2, fuel_liters: 420, idle_time_mins: 65, efficiency_index: 88 },
      { waybill_id: 'WB-4002', dispatch_date: '2026-07-05', corridor_hub: 'Midwest Central', cargo_weight_tons: 31.2, transit_duration_hrs: 24.8, fuel_liters: 610, idle_time_mins: 110, efficiency_index: 74 },
      { waybill_id: 'WB-4003', dispatch_date: '2026-07-08', corridor_hub: 'Atlantic Coast', cargo_weight_tons: 16.8, transit_duration_hrs: 12.4, fuel_liters: 285, idle_time_mins: 35, efficiency_index: 93 },
      { waybill_id: 'WB-4004', dispatch_date: '2026-07-12', corridor_hub: 'Gulf Express', cargo_weight_tons: 28.0, transit_duration_hrs: 21.5, fuel_liters: 530, idle_time_mins: 90, efficiency_index: 79 },
      { waybill_id: 'WB-4005', dispatch_date: '2026-07-15', corridor_hub: 'Pacific Gateway', cargo_weight_tons: 26.4, transit_duration_hrs: 19.1, fuel_liters: 445, idle_time_mins: 55, efficiency_index: 86 },
      { waybill_id: 'WB-4006', dispatch_date: '2026-07-19', corridor_hub: 'Midwest Central', cargo_weight_tons: 33.5, transit_duration_hrs: 26.3, fuel_liters: 660, idle_time_mins: 135, efficiency_index: 68 },
      { waybill_id: 'WB-4007', dispatch_date: '2026-07-22', corridor_hub: 'Atlantic Coast', cargo_weight_tons: 18.2, transit_duration_hrs: 13.0, fuel_liters: 305, idle_time_mins: 40, efficiency_index: 91 },
      { waybill_id: 'WB-4008', dispatch_date: '2026-07-26', corridor_hub: 'Gulf Express', cargo_weight_tons: 29.8, transit_duration_hrs: 22.8, fuel_liters: 565, idle_time_mins: 95, efficiency_index: 77 },
      { waybill_id: 'WB-4009', dispatch_date: '2026-07-30', corridor_hub: 'Pacific Gateway', cargo_weight_tons: 23.0, transit_duration_hrs: 17.5, fuel_liters: 395, idle_time_mins: 48, efficiency_index: 90 },
      { waybill_id: 'WB-4010', dispatch_date: '2026-08-03', corridor_hub: 'Midwest Central', cargo_weight_tons: 30.5, transit_duration_hrs: 23.9, fuel_liters: 590, idle_time_mins: 105, efficiency_index: 76 },
      { waybill_id: 'WB-4011', dispatch_date: '2026-08-06', corridor_hub: 'Atlantic Coast', cargo_weight_tons: 15.5, transit_duration_hrs: 11.8, fuel_liters: 270, idle_time_mins: 30, efficiency_index: 95 },
      { waybill_id: 'WB-4012', dispatch_date: '2026-08-10', corridor_hub: 'Gulf Express', cargo_weight_tons: 27.2, transit_duration_hrs: 20.6, fuel_liters: 510, idle_time_mins: 80, efficiency_index: 82 }
    ]
  },
  {
    id: 'ds-energy-03',
    projectId: 'proj-clean-power',
    name: 'Renewable Turbine Grid & Telemetry',
    description: 'Wind speed sensors, megawatt generation output, rotor RPM, ambient temperatures, and vibration stability metrics.',
    domain: 'Clean Tech & Industrial IoT',
    rowCount: 280,
    columnCount: 8,
    fileType: 'csv',
    status: 'ready',
    sizeBytes: 160000,
    uploadedAt: '2026-08-11T16:45:00Z',
    tags: ['wind', 'turbine', 'megawatts', 'vibration'],
    columns: [
      { name: 'Turbine Unit', key: 'turbine_id', originalName: 'turbine_id', dataType: 'id', description: 'Turbine array asset identifier' },
      { name: 'Timestamp', key: 'reading_time', originalName: 'reading_time', dataType: 'datetime', description: 'Sensor recording timestamp' },
      { name: 'Turbine Cluster', key: 'cluster_zone', originalName: 'cluster_zone', dataType: 'categorical', description: 'Geographic farm cluster zone' },
      { name: 'Wind Velocity (m/s)', key: 'wind_speed_mps', originalName: 'wind_speed_mps', dataType: 'numeric', description: 'Anemometer wind speed' },
      { name: 'Power Generation (MW)', key: 'power_output_mw', originalName: 'power_output_mw', dataType: 'numeric', description: 'Instantaneous megawatt generation' },
      { name: 'Rotor Speed (RPM)', key: 'rotor_rpm', originalName: 'rotor_rpm', dataType: 'numeric', description: 'Turbine shaft rotations per minute' },
      { name: 'Vibration Amplitude (mm/s)', key: 'vibration_level', originalName: 'vibration_level', dataType: 'numeric', description: 'Bearing vibration telemetry' },
      { name: 'Grid Capacity Utilization (%)', key: 'capacity_factor_pct', originalName: 'capacity_factor_pct', dataType: 'numeric', description: 'Actual vs rated output percentage' }
    ],
    sampleRows: [
      { turbine_id: 'WT-01', reading_time: '2026-07-01', cluster_zone: 'North Ridge', wind_speed_mps: 11.2, power_output_mw: 3.42, rotor_rpm: 14.8, vibration_level: 1.8, capacity_factor_pct: 85.5 },
      { turbine_id: 'WT-02', reading_time: '2026-07-04', cluster_zone: 'East Valley', wind_speed_mps: 7.8, power_output_mw: 1.95, rotor_rpm: 10.4, vibration_level: 1.2, capacity_factor_pct: 48.7 },
      { turbine_id: 'WT-03', reading_time: '2026-07-08', cluster_zone: 'Highland Plateau', wind_speed_mps: 13.5, power_output_mw: 3.98, rotor_rpm: 16.2, vibration_level: 2.6, capacity_factor_pct: 99.5 },
      { turbine_id: 'WT-04', reading_time: '2026-07-12', cluster_zone: 'Coastal Sector', wind_speed_mps: 9.4, power_output_mw: 2.70, rotor_rpm: 12.6, vibration_level: 1.5, capacity_factor_pct: 67.5 },
      { turbine_id: 'WT-05', reading_time: '2026-07-16', cluster_zone: 'North Ridge', wind_speed_mps: 12.0, power_output_mw: 3.65, rotor_rpm: 15.1, vibration_level: 2.1, capacity_factor_pct: 91.2 },
      { turbine_id: 'WT-06', reading_time: '2026-07-20', cluster_zone: 'East Valley', wind_speed_mps: 6.9, power_output_mw: 1.62, rotor_rpm: 9.6, vibration_level: 1.1, capacity_factor_pct: 40.5 },
      { turbine_id: 'WT-07', reading_time: '2026-07-24', cluster_zone: 'Highland Plateau', wind_speed_mps: 14.1, power_output_mw: 4.00, rotor_rpm: 16.8, vibration_level: 3.1, capacity_factor_pct: 100.0 },
      { turbine_id: 'WT-08', reading_time: '2026-07-28', cluster_zone: 'Coastal Sector', wind_speed_mps: 10.1, power_output_mw: 3.05, rotor_rpm: 13.4, vibration_level: 1.7, capacity_factor_pct: 76.2 },
      { turbine_id: 'WT-09', reading_time: '2026-08-01', cluster_zone: 'North Ridge', wind_speed_mps: 11.8, power_output_mw: 3.55, rotor_rpm: 15.0, vibration_level: 1.9, capacity_factor_pct: 88.8 },
      { turbine_id: 'WT-10', reading_time: '2026-08-05', cluster_zone: 'East Valley', wind_speed_mps: 8.5, power_output_mw: 2.30, rotor_rpm: 11.5, vibration_level: 1.4, capacity_factor_pct: 57.5 },
      { turbine_id: 'WT-11', reading_time: '2026-08-09', cluster_zone: 'Highland Plateau', wind_speed_mps: 12.8, power_output_mw: 3.82, rotor_rpm: 15.8, vibration_level: 2.4, capacity_factor_pct: 95.5 },
      { turbine_id: 'WT-12', reading_time: '2026-08-13', cluster_zone: 'Coastal Sector', wind_speed_mps: 9.8, power_output_mw: 2.88, rotor_rpm: 13.0, vibration_level: 1.6, capacity_factor_pct: 72.0 }
    ]
  },
  {
    id: 'ds-academic-04',
    projectId: 'proj-edutech',
    name: 'Higher Ed Student Engagement & Grades',
    description: 'Attendance percentages, weekly study hours, lab completions, midterm scores, and final GPA outcomes across academic faculties.',
    domain: 'Education & Institutional Research',
    rowCount: 260,
    columnCount: 8,
    fileType: 'csv',
    status: 'ready',
    sizeBytes: 150000,
    uploadedAt: '2026-08-09T11:20:00Z',
    tags: ['education', 'grades', 'attendance', 'students'],
    columns: [
      { name: 'Student Matriculation', key: 'student_id', originalName: 'student_id', dataType: 'id', description: 'Student identifier' },
      { name: 'Semester Term', key: 'term_date', originalName: 'term_date', dataType: 'datetime', description: 'Academic term date' },
      { name: 'Academic Faculty', key: 'faculty_name', originalName: 'faculty_name', dataType: 'categorical', description: 'College faculty department' },
      { name: 'Attendance Rate (%)', key: 'attendance_pct', originalName: 'attendance_pct', dataType: 'numeric', description: 'Class session presence percentage' },
      { name: 'Weekly Study Hours', key: 'weekly_study_hrs', originalName: 'weekly_study_hrs', dataType: 'numeric', description: 'Self-reported and LMS study time' },
      { name: 'Lab Submissions Done', key: 'labs_completed', originalName: 'labs_completed', dataType: 'numeric', description: 'Completed practical coursework' },
      { name: 'Quiz Average (%)', key: 'quiz_average_pct', originalName: 'quiz_average_pct', dataType: 'numeric', description: 'Cumulative formative assessment scores' },
      { name: 'Final Course Grade (%)', key: 'final_grade_pct', originalName: 'final_grade_pct', dataType: 'numeric', description: 'Term final grade score' }
    ],
    sampleRows: [
      { student_id: 'STU-101', term_date: '2026-07-01', faculty_name: 'Computer Science', attendance_pct: 94.5, weekly_study_hrs: 18.5, labs_completed: 10, quiz_average_pct: 91.2, final_grade_pct: 93.4 },
      { student_id: 'STU-102', term_date: '2026-07-04', faculty_name: 'Biomedical Science', attendance_pct: 88.0, weekly_study_hrs: 14.0, labs_completed: 8, quiz_average_pct: 82.5, final_grade_pct: 84.0 },
      { student_id: 'STU-103', term_date: '2026-07-07', faculty_name: 'Civil Engineering', attendance_pct: 72.5, weekly_study_hrs: 8.5, labs_completed: 6, quiz_average_pct: 68.0, final_grade_pct: 69.5 },
      { student_id: 'STU-104', term_date: '2026-07-11', faculty_name: 'Economics & Math', attendance_pct: 96.0, weekly_study_hrs: 21.0, labs_completed: 10, quiz_average_pct: 95.0, final_grade_pct: 96.8 },
      { student_id: 'STU-105', term_date: '2026-07-15', faculty_name: 'Computer Science', attendance_pct: 89.2, weekly_study_hrs: 15.5, labs_completed: 9, quiz_average_pct: 86.4, final_grade_pct: 88.0 },
      { student_id: 'STU-106', term_date: '2026-07-19', faculty_name: 'Biomedical Science', attendance_pct: 79.0, weekly_study_hrs: 10.5, labs_completed: 7, quiz_average_pct: 74.2, final_grade_pct: 76.5 },
      { student_id: 'STU-107', term_date: '2026-07-23', faculty_name: 'Civil Engineering', attendance_pct: 91.0, weekly_study_hrs: 16.5, labs_completed: 9, quiz_average_pct: 88.0, final_grade_pct: 89.2 },
      { student_id: 'STU-108', term_date: '2026-07-27', faculty_name: 'Economics & Math', attendance_pct: 84.5, weekly_study_hrs: 12.0, labs_completed: 8, quiz_average_pct: 79.5, final_grade_pct: 81.0 },
      { student_id: 'STU-109', term_date: '2026-07-31', faculty_name: 'Computer Science', attendance_pct: 98.0, weekly_study_hrs: 22.5, labs_completed: 10, quiz_average_pct: 97.5, final_grade_pct: 98.2 },
      { student_id: 'STU-110', term_date: '2026-08-04', faculty_name: 'Biomedical Science', attendance_pct: 86.5, weekly_study_hrs: 13.5, labs_completed: 8, quiz_average_pct: 81.0, final_grade_pct: 83.2 },
      { student_id: 'STU-111', term_date: '2026-08-08', faculty_name: 'Civil Engineering', attendance_pct: 69.0, weekly_study_hrs: 7.0, labs_completed: 5, quiz_average_pct: 63.5, final_grade_pct: 65.0 },
      { student_id: 'STU-112', term_date: '2026-08-12', faculty_name: 'Economics & Math', attendance_pct: 93.0, weekly_study_hrs: 17.5, labs_completed: 9, quiz_average_pct: 90.0, final_grade_pct: 91.5 }
    ]
  },
  {
    id: 'ds-saas-05',
    projectId: 'proj-platform-ops',
    name: 'SaaS Platform Activity & Retention',
    description: 'Daily active sessions, API compute throughput, feature adoption indices, latency metrics, and cohort health scores.',
    domain: 'Software & Cloud Telemetry',
    rowCount: 350,
    columnCount: 8,
    fileType: 'json',
    status: 'ready',
    sizeBytes: 210000,
    uploadedAt: '2026-08-08T18:00:00Z',
    tags: ['saas', 'telemetry', 'api', 'retention'],
    columns: [
      { name: 'Workspace Tenant', key: 'tenant_id', originalName: 'tenant_id', dataType: 'id', description: 'Cloud tenant identifier' },
      { name: 'Activity Date', key: 'event_date', originalName: 'event_date', dataType: 'datetime', description: 'Telemetry date' },
      { name: 'Tier Plan', key: 'service_tier', originalName: 'service_tier', dataType: 'categorical', description: 'Subscription tier level' },
      { name: 'Session Minutes', key: 'session_duration_mins', originalName: 'session_duration_mins', dataType: 'numeric', description: 'Average active console duration' },
      { name: 'API Calls (Thousands)', key: 'api_volume_k', originalName: 'api_volume_k', dataType: 'numeric', description: 'Compute requests per day' },
      { name: 'Avg Endpoint Latency (ms)', key: 'latency_ms', originalName: 'latency_ms', dataType: 'numeric', description: 'p95 API response duration' },
      { name: 'Feature Adoption Score', key: 'adoption_score', originalName: 'adoption_score', dataType: 'numeric', description: 'Breadth of modules activated (0-100)' },
      { name: 'Retention Health Index', key: 'health_index', originalName: 'health_index', dataType: 'numeric', description: 'Composite account stability score' }
    ],
    sampleRows: [
      { tenant_id: 'ORG-901', event_date: '2026-07-03', service_tier: 'Enterprise Dedicated', session_duration_mins: 280, api_volume_k: 450, latency_ms: 38, adoption_score: 92, health_index: 96 },
      { tenant_id: 'ORG-902', event_date: '2026-07-06', service_tier: 'Scale Growth', session_duration_mins: 145, api_volume_k: 180, latency_ms: 54, adoption_score: 76, health_index: 84 },
      { tenant_id: 'ORG-903', event_date: '2026-07-09', service_tier: 'Starter Developer', session_duration_mins: 45, api_volume_k: 22, latency_ms: 72, adoption_score: 41, health_index: 62 },
      { tenant_id: 'ORG-904', event_date: '2026-07-13', service_tier: 'Enterprise Dedicated', session_duration_mins: 310, api_volume_k: 520, latency_ms: 41, adoption_score: 95, health_index: 98 },
      { tenant_id: 'ORG-905', event_date: '2026-07-17', service_tier: 'Scale Growth', session_duration_mins: 160, api_volume_k: 210, latency_ms: 49, adoption_score: 80, health_index: 87 },
      { tenant_id: 'ORG-906', event_date: '2026-07-21', service_tier: 'Starter Developer', session_duration_mins: 38, api_volume_k: 18, latency_ms: 85, adoption_score: 35, health_index: 55 },
      { tenant_id: 'ORG-907', event_date: '2026-07-25', service_tier: 'Enterprise Dedicated', session_duration_mins: 295, api_volume_k: 480, latency_ms: 36, adoption_score: 94, health_index: 97 },
      { tenant_id: 'ORG-908', event_date: '2026-07-29', service_tier: 'Scale Growth', session_duration_mins: 155, api_volume_k: 195, latency_ms: 52, adoption_score: 78, health_index: 85 },
      { tenant_id: 'ORG-909', event_date: '2026-08-02', service_tier: 'Starter Developer', session_duration_mins: 50, api_volume_k: 28, latency_ms: 68, adoption_score: 44, health_index: 65 },
      { tenant_id: 'ORG-910', event_date: '2026-08-06', service_tier: 'Enterprise Dedicated', session_duration_mins: 325, api_volume_k: 560, latency_ms: 39, adoption_score: 96, health_index: 99 },
      { tenant_id: 'ORG-911', event_date: '2026-08-10', service_tier: 'Scale Growth', session_duration_mins: 170, api_volume_k: 225, latency_ms: 47, adoption_score: 82, health_index: 89 },
      { tenant_id: 'ORG-912', event_date: '2026-08-14', service_tier: 'Starter Developer', session_duration_mins: 42, api_volume_k: 20, latency_ms: 78, adoption_score: 38, health_index: 58 }
    ]
  }
];
